// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqKnsnvmPAnkNnRnPQLO4K2UltKpqX8Q',
    appId: '1:619652789578:web:2ee3ac33b552b597f93db3',
    messagingSenderId: '619652789578',
    projectId: 'go-volunteer-ba404',
    authDomain: 'go-volunteer-ba404.firebaseapp.com',
    storageBucket: 'go-volunteer-ba404.appspot.com',
    measurementId: 'G-F2XB3CBEL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATslRnrqgJ7gbedo_fM5oZySVrKB0h6BU',
    appId: '1:619652789578:android:2987e10f92eb345bf93db3',
    messagingSenderId: '619652789578',
    projectId: 'go-volunteer-ba404',
    storageBucket: 'go-volunteer-ba404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6uH6OzdYfWlKcY7mC-bODUAussH6N18',
    appId: '1:619652789578:ios:9338727d26ea6186f93db3',
    messagingSenderId: '619652789578',
    projectId: 'go-volunteer-ba404',
    storageBucket: 'go-volunteer-ba404.appspot.com',
    iosBundleId: 'com.example.goVolunteer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6uH6OzdYfWlKcY7mC-bODUAussH6N18',
    appId: '1:619652789578:ios:9338727d26ea6186f93db3',
    messagingSenderId: '619652789578',
    projectId: 'go-volunteer-ba404',
    storageBucket: 'go-volunteer-ba404.appspot.com',
    iosBundleId: 'com.example.goVolunteer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqKnsnvmPAnkNnRnPQLO4K2UltKpqX8Q',
    appId: '1:619652789578:web:9793395005f57d45f93db3',
    messagingSenderId: '619652789578',
    projectId: 'go-volunteer-ba404',
    authDomain: 'go-volunteer-ba404.firebaseapp.com',
    storageBucket: 'go-volunteer-ba404.appspot.com',
    measurementId: 'G-Q44YDNY3R5',
  );
}
